- .release-please-manifest.json
> manifest json

- .github/workflows/release.yml
- .release-please-manifest.json
> fix: test release please fix

- .release-please-manifest.json
- package.json
- packages/core/package.json
- packages/react/package.json
> publish lower

- .release-please-manifest.json
> fix: bump version

- demo/with-next/package.json
- package.json
- pnpm-lock.yaml
Fix critical packages inside of minikit demo
> fix critical packages

- demo/with-next/components/ClientContent/ShareContacts.tsx
- demo/with-next/components/ClientContent/index.tsx
- packages/core/minikit.ts
- packages/core/types/commands.ts
- packages/core/types/errors.ts
- packages/core/types/responses.ts
> feat: Share contacts command

- .release-please-manifest.json
- package.json
- packages/core/package.json
- packages/react/package.json
> Bump Version

- .github/workflows/release.yml
See `release-please-action` README: https://github.com/googleapis/release-please-action/tree/v3.7.13?tab=readme-ov-file#workflow-permissions
> fix: add permissions to workflow file

- README.md
- packages/core/README.md
- packages/core/package.json
- packages/react/README.md
- packages/react/package.json
- packages/react/src/components/index.ts
- packages/react/src/components/username-search.tsx
- packages/react/src/index.ts
- packages/react/tsconfig.json
Simple component to get usernames search up quickly!
i also adjusted MiniKit casing in some places 😄 
search endpoint not available yet, do not merge
> Usernames search

- packages/core/helpers/usernames/index.ts
fixes a _really_ stupid error on my part when parsing response from username query
> fix: username query parsing

- .github/workflows/release.yml
- package.json
fix pnpm version mismatch for release-please
> fix: pnpm version

- packages/core/helpers/address-book/index.ts
- packages/core/helpers/payment/client.ts
- packages/core/helpers/siwe/validate-wallet-auth-command-input.ts
- packages/core/index.ts
- packages/core/minikit.ts
- packages/react/src/address-book/index.ts
- packages/react/src/address-book/is-verified.tsx
- packages/react/src/index.ts
feature implementation, import cleanup
> feat: isUserVerified helper & react bindings

- packages/core/helpers/siwe/siwe.ts
- packages/core/minikit.ts
> Remove Optimism

- release-please-config.json
> fix group name

- packages/core/minikit.ts
> fix: chain ID to worldchain

- packages/react/package.json
- pnpm-lock.yaml
> Fix deploy

- .github/workflows/release.yml
Release please still doesn't work trying to fix
> Try to fix release

- .github/workflows/release.yml
> fix config

- .github/workflows/ci.yml
> fix: set runner to 24.04

- .github/workflows/create-manifest.yml
- .github/workflows/release.yml
Deployment still not working. I think this fixes it
> update release ci

- demo/with-next/package.json
- packages/core/package.json
- packages/react/package.json
- packages/react/src/transaction/hooks.ts
- pnpm-lock.yaml
bump viem, use uniform versions across packages and fix typings
> update viem, better types for client in hook

- packages/react/src/transaction/hooks.ts
> actually pass generics

- demo/with-next/app/api/nonce/route.ts
- demo/with-next/components/ClientContent/CheckRequests.tsx
- demo/with-next/components/ClientContent/GetPermissions.tsx
- demo/with-next/components/ClientContent/SignMessage.tsx
- demo/with-next/components/ClientContent/index.tsx
- packages/core/helpers/transaction/validate-payload.ts
- packages/core/minikit.ts
- packages/core/tests/validate-payload.test.ts
- packages/core/types/commands.ts
- packages/core/types/errors.ts
- packages/core/types/responses.ts
> Release 1.7

- packages/core/helpers/proof/index.ts
- packages/core/minikit.ts
- packages/core/package.json
- pnpm-lock.yaml
> WIP: compress proofs via RPC call

- packages/core/helpers/proof/index.ts
- packages/core/minikit.ts
> Proof compression

- demo/with-next/components/ClientContent/Camera.tsx
- demo/with-next/components/ClientContent/ExternalLinks.tsx
- demo/with-next/components/ClientContent/VerifyAction/index.tsx
- packages/core/helpers/proof/index.ts
- packages/core/helpers/transaction/validate-payload.ts
- packages/core/minikit.ts
- packages/core/package.json
- packages/core/tests/validate-payload.test.ts
- packages/core/types/commands.ts
- packages/core/types/errors.ts
- packages/react/src/transaction/hooks.ts
- pnpm-lock.yaml
- Fix big in parsing
- Proof compression
- New IDKit to support additional verification levels
> Release 1.8

- demo/with-next/components/ClientContent/Transaction.tsx
- [ x] Bug Fix
Missing contract
> add contract

- demo/with-next/app/test/page.tsx
- demo/with-next/components/ClientContent/SearchParams.tsx
- packages/core/helpers/siwe/siwe.ts
> add new page

- demo/next-15-template/package.json
> use latest

- packages/create-world-mini-app/package.json
- packages/create-world-mini-app/src/index.ts
Degit can't find github specifying this should help
> Degit can't find github

- demo/with-next/components/ClientContent/ExternalLinks.tsx
> add collection deeplinks to test app

- demo/next-15-template/README.md
- Updated broken link to Mini Apps UI Kit (https://github.com/worldcoin/mini-apps-ui-kit)
> Fix link to Mini Apps UI Kit repository

- demo/with-next/abi/MinikitStaging.json
- packages/core/package.json
- packages/core/tests/siwe.test.ts
- pnpm-lock.yaml
Add a test for SIWE. Some general cleanup too
> Add SIWE test

- packages/core/minikit.ts
Fix versioning issues. Temporarily to unblock a dev and fix it more later on properly
> Fix Versioning

- demo/next-15-template/src/components/Transaction/index.tsx
- demo/with-next/components/ClientContent/SignTypedMessage.tsx
> use client id

- demo/next-15-template/src/components/Transaction/index.tsx
- packages/core/minikit.ts
> Fixes files

- packages/core/minikit.ts
> Add minor version

- packages/core/helpers/microphone/index.ts
> fix one more

- demo/with-next/components/ClientContent/SendHaptic.tsx
- packages/core/minikit.ts
- packages/core/tests/microphone.test.ts
- packages/core/types/commands.ts
> Revert "fix: add missing haptic styles 'soft' and 'rigid'"

- demo/with-next/components/ClientContent/SendHaptic.tsx
- packages/core/minikit.ts
- packages/core/tests/microphone.test.ts
- packages/core/types/commands.ts
Yes checked on android too doesn't work
> Revert "Revert "Revert "fix: add missing haptic styles 'soft' and 'rigid'"""
